services:
  app:
    container_name: bank-java-app
    image: assignment:latest
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
        restart: true
      mq:
        condition: service_started
    build:
      context: .

  db:
    image: postgres:18
    container_name: bank-postgres
    environment:
      POSTGRES_DB: bank-accounts
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=user --dbname=bank-accounts"]
      interval: 5s
      timeout: 5s
      retries: 20

  mq:
    image: rabbitmq:4-management
    container_name: bank-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
